spring:
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                globally_quoted_identifiers: true
    datasource:
        url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/banking-db
        username: postgres
        password: 138294
        driver-class-name: org.postgresql.Driver
    thymeleaf:
        cache: false